baseURL = 'https://monoid.github.io/'
languageCode = 'en-us'
title = 'Monoidal Tranformation'
theme = 'PaperMod'
author = 'Ivan Boldyrev'
copyright = "Copyright © 2025, Ivan Boldyrev; all rights reserved."

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
ShowShareButtons = true
ShareButtons = ["x", "linkedin", "reddit", "facebook"]
